export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const FILTER_SERVICES = 'FILTER_SERVICES';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CANCEL_EDIT_SERVICE = 'CANCEL_EDIT_SERVICE';
